// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"net/url"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/techbloghub/server/ent/company"
	"github.com/techbloghub/server/ent/predicate"
)

// CompanyUpdate is the builder for updating Company entities.
type CompanyUpdate struct {
	config
	hooks    []Hook
	mutation *CompanyMutation
}

// Where appends a list predicates to the CompanyUpdate builder.
func (cu *CompanyUpdate) Where(ps ...predicate.Company) *CompanyUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUpdateTime sets the "update_time" field.
func (cu *CompanyUpdate) SetUpdateTime(t time.Time) *CompanyUpdate {
	cu.mutation.SetUpdateTime(t)
	return cu
}

// SetDeleteTime sets the "delete_time" field.
func (cu *CompanyUpdate) SetDeleteTime(t time.Time) *CompanyUpdate {
	cu.mutation.SetDeleteTime(t)
	return cu
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (cu *CompanyUpdate) SetNillableDeleteTime(t *time.Time) *CompanyUpdate {
	if t != nil {
		cu.SetDeleteTime(*t)
	}
	return cu
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (cu *CompanyUpdate) ClearDeleteTime() *CompanyUpdate {
	cu.mutation.ClearDeleteTime()
	return cu
}

// SetName sets the "name" field.
func (cu *CompanyUpdate) SetName(s string) *CompanyUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cu *CompanyUpdate) SetNillableName(s *string) *CompanyUpdate {
	if s != nil {
		cu.SetName(*s)
	}
	return cu
}

// SetLogoURL sets the "logo_url" field.
func (cu *CompanyUpdate) SetLogoURL(u *url.URL) *CompanyUpdate {
	cu.mutation.SetLogoURL(u)
	return cu
}

// SetBlogURL sets the "blog_url" field.
func (cu *CompanyUpdate) SetBlogURL(u *url.URL) *CompanyUpdate {
	cu.mutation.SetBlogURL(u)
	return cu
}

// SetRssURL sets the "rss_url" field.
func (cu *CompanyUpdate) SetRssURL(u *url.URL) *CompanyUpdate {
	cu.mutation.SetRssURL(u)
	return cu
}

// Mutation returns the CompanyMutation object of the builder.
func (cu *CompanyUpdate) Mutation() *CompanyMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CompanyUpdate) Save(ctx context.Context) (int, error) {
	if err := cu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CompanyUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CompanyUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CompanyUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *CompanyUpdate) defaults() error {
	if _, ok := cu.mutation.UpdateTime(); !ok {
		if company.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized company.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := company.UpdateDefaultUpdateTime()
		cu.mutation.SetUpdateTime(v)
	}
	return nil
}

func (cu *CompanyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(company.Table, company.Columns, sqlgraph.NewFieldSpec(company.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UpdateTime(); ok {
		_spec.SetField(company.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := cu.mutation.DeleteTime(); ok {
		_spec.SetField(company.FieldDeleteTime, field.TypeTime, value)
	}
	if cu.mutation.DeleteTimeCleared() {
		_spec.ClearField(company.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(company.FieldName, field.TypeString, value)
	}
	if value, ok := cu.mutation.LogoURL(); ok {
		vv, err := company.ValueScanner.LogoURL.Value(value)
		if err != nil {
			return 0, err
		}
		_spec.SetField(company.FieldLogoURL, field.TypeString, vv)
	}
	if value, ok := cu.mutation.BlogURL(); ok {
		vv, err := company.ValueScanner.BlogURL.Value(value)
		if err != nil {
			return 0, err
		}
		_spec.SetField(company.FieldBlogURL, field.TypeString, vv)
	}
	if value, ok := cu.mutation.RssURL(); ok {
		vv, err := company.ValueScanner.RssURL.Value(value)
		if err != nil {
			return 0, err
		}
		_spec.SetField(company.FieldRssURL, field.TypeString, vv)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{company.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CompanyUpdateOne is the builder for updating a single Company entity.
type CompanyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CompanyMutation
}

// SetUpdateTime sets the "update_time" field.
func (cuo *CompanyUpdateOne) SetUpdateTime(t time.Time) *CompanyUpdateOne {
	cuo.mutation.SetUpdateTime(t)
	return cuo
}

// SetDeleteTime sets the "delete_time" field.
func (cuo *CompanyUpdateOne) SetDeleteTime(t time.Time) *CompanyUpdateOne {
	cuo.mutation.SetDeleteTime(t)
	return cuo
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (cuo *CompanyUpdateOne) SetNillableDeleteTime(t *time.Time) *CompanyUpdateOne {
	if t != nil {
		cuo.SetDeleteTime(*t)
	}
	return cuo
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (cuo *CompanyUpdateOne) ClearDeleteTime() *CompanyUpdateOne {
	cuo.mutation.ClearDeleteTime()
	return cuo
}

// SetName sets the "name" field.
func (cuo *CompanyUpdateOne) SetName(s string) *CompanyUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cuo *CompanyUpdateOne) SetNillableName(s *string) *CompanyUpdateOne {
	if s != nil {
		cuo.SetName(*s)
	}
	return cuo
}

// SetLogoURL sets the "logo_url" field.
func (cuo *CompanyUpdateOne) SetLogoURL(u *url.URL) *CompanyUpdateOne {
	cuo.mutation.SetLogoURL(u)
	return cuo
}

// SetBlogURL sets the "blog_url" field.
func (cuo *CompanyUpdateOne) SetBlogURL(u *url.URL) *CompanyUpdateOne {
	cuo.mutation.SetBlogURL(u)
	return cuo
}

// SetRssURL sets the "rss_url" field.
func (cuo *CompanyUpdateOne) SetRssURL(u *url.URL) *CompanyUpdateOne {
	cuo.mutation.SetRssURL(u)
	return cuo
}

// Mutation returns the CompanyMutation object of the builder.
func (cuo *CompanyUpdateOne) Mutation() *CompanyMutation {
	return cuo.mutation
}

// Where appends a list predicates to the CompanyUpdate builder.
func (cuo *CompanyUpdateOne) Where(ps ...predicate.Company) *CompanyUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CompanyUpdateOne) Select(field string, fields ...string) *CompanyUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Company entity.
func (cuo *CompanyUpdateOne) Save(ctx context.Context) (*Company, error) {
	if err := cuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CompanyUpdateOne) SaveX(ctx context.Context) *Company {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CompanyUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CompanyUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *CompanyUpdateOne) defaults() error {
	if _, ok := cuo.mutation.UpdateTime(); !ok {
		if company.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized company.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := company.UpdateDefaultUpdateTime()
		cuo.mutation.SetUpdateTime(v)
	}
	return nil
}

func (cuo *CompanyUpdateOne) sqlSave(ctx context.Context) (_node *Company, err error) {
	_spec := sqlgraph.NewUpdateSpec(company.Table, company.Columns, sqlgraph.NewFieldSpec(company.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Company.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, company.FieldID)
		for _, f := range fields {
			if !company.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != company.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UpdateTime(); ok {
		_spec.SetField(company.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.DeleteTime(); ok {
		_spec.SetField(company.FieldDeleteTime, field.TypeTime, value)
	}
	if cuo.mutation.DeleteTimeCleared() {
		_spec.ClearField(company.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(company.FieldName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.LogoURL(); ok {
		vv, err := company.ValueScanner.LogoURL.Value(value)
		if err != nil {
			return nil, err
		}
		_spec.SetField(company.FieldLogoURL, field.TypeString, vv)
	}
	if value, ok := cuo.mutation.BlogURL(); ok {
		vv, err := company.ValueScanner.BlogURL.Value(value)
		if err != nil {
			return nil, err
		}
		_spec.SetField(company.FieldBlogURL, field.TypeString, vv)
	}
	if value, ok := cuo.mutation.RssURL(); ok {
		vv, err := company.ValueScanner.RssURL.Value(value)
		if err != nil {
			return nil, err
		}
		_spec.SetField(company.FieldRssURL, field.TypeString, vv)
	}
	_node = &Company{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{company.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
