-- Create "tags" table
CREATE TABLE "tags"(
    "id"          bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "create_time" timestamptz       NOT NULL,
    "update_time" timestamptz       NOT NULL,
    "delete_time" timestamptz NULL,
    "name"        character varying NOT NULL,
    PRIMARY KEY ("id")
);

-- Create unique index "tags_name_key" to table: "tags"
CREATE UNIQUE INDEX "tags_name_key" ON "tags" ("name");

-- Ensure pg_trgm extension is installed
CREATE
EXTENSION IF NOT EXISTS pg_trgm;

-- Create Tri-Gram GIN index on "name" column
CREATE INDEX "tags_name_trgm_idx" ON "tags" USING gin ("name" gin_trgm_ops);
