name: backend test for PR to main

on:
  push:
    branches: [ "cicd-test" ]
  pull_request:
    branches: [ "cicd-test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV }}" > .env

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test ./...