// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// CompanyOrErr calls the predicate only if the error is not nit.
func CompanyOrErr(p Company, err error) Company {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
